### ISSUE TITLE
Support Firefox

### ISSUE THREAD

**Issue by cezaraugusto** [cezaraugusto/extension.js#5]
Most likely to be solved by a custom/external plugin.

**Comment by dotproto** [comment]
Can you share more about on what is currently missing to support Firefox? I may be able to lend a hand or at least provide some relevant information.

**Comment by CMCDragonkai** [comment]
You have firefox already ticked, does that mean it's working?

![image](https://github.com/cezaraugusto/extension.js/assets/640797/f104b610-2162-4c19-8a7e-4cc2f52c88d9)

**Comment by strawberrymelonpanda** [comment]
@CMCDragonkai Looks like it was added 2 days ago 6c7c00257038e2698fc06a1dc06a229953f26281. 

Thanks for mentioning, I was watching this issue expecting it'd get updated or closed.

**Comment by CMCDragonkai** [comment]
I wonder if this will solve the chrome and Firefox having different requirements for background scripts like service worker vs background script.

**Comment by cezaraugusto** [comment]
@dotproto - sure! so each browser is represented as a webpack plugin. for example, you can see the implementation for Chrome [here](https://github.com/cezaraugusto/extension.js/tree/main/packages/run-chrome-extension). I've committed a fork of Chrome for Firefox [here](https://github.com/cezaraugusto/extension.js/tree/main/packages/run-firefox-extension) with some defaults, but there's still work to be done.

@CMCDragonkai, @strawberrymelonpanda - thanks for pointing that out! Extension.js does support Firefox, but unlike Chrome/Edge, it does not automatically run the browser for you. feel free to open a pull request updating the README.md, and I'll approve it. I added the information by mistake when I was adding the boilerplate code for the plugin.

@CMCDragonkai - regarding the manifest differences, we may eventually need to handle running multiple browsers with different manifest fields at once, so having both MV2 and MV3 background fields will likely break something. Firefox support will handle extensions as if you had added them manually as a temporary extension. I hope that clarifies things :)

**Comment by CMCDragonkai** [comment]
What about: https://stackoverflow.com/a/78088358

But a comment said it wasn't accepted. Maybe maintaining dual manifests is required?

**Comment by cezaraugusto** [comment]
@CMCDragonkai more likely a custom browser prefix for browser-specific fields in case you are running multiple browsers at once, like:

```json5
{
  "background": {
    "service_worker": "sw.js", // runs for all browsers
    "edge:service_worker": "sw.js", // runs for Edge only
    "firefox:scripts": [] , // runs for Firefox only
  }
}
```

But this is not implemented yet.

**Comment by cezaraugusto** [comment]
Firefox support is live in v1.5.0! Here's a sample run using [firefox-code-search](https://github.com/mdn/webextensions-examples/tree/main/firefox-code-search) sample from MDN:

```sh
npx extension@latest dev https://github.com/mdn/webextensions-examples/tree/main/firefox-code-search --browser=firefox
```

https://github.com/cezaraugusto/extension.js/assets/4672033/e94ca464-663f-4724-8670-a18c1003f976

**Comment by CMCDragonkai** [comment]
That's great. Is there an example of an extension that is both firefox and chromium.

```
{
  "background": {
    "service_worker": "sw.js", // runs for all browsers
    "edge:service_worker": "sw.js", // runs for Edge only
    "firefox:scripts": [] , // runs for Firefox only
  }
}
```

Do I use this...?
