### ISSUE TITLE
Is there a plan to support Vue?

### ISSUE THREAD

**Issue by code4you2021** [cezaraugusto/extension.js#52]

**Comment by cezaraugusto** [comment]
There is!

This would be mostly a matter of adding a new template to https://github.com/cezaraugusto/extension.js/tree/main/programs/create/templates. The program should handle the rest automatically.

At the moment I'm focusing on browser support, so if you/someone is familiar with Vue and would like to add it, I'd love to see a vue/vue-typescript template. The React templates might be good samples to fork and adapt.

Open for grabs!

**Comment by cezaraugusto** [comment]
@OSpoon Extension.js is built on top of webpack, but there is no plan to expose the config for now. I'm open to implement new libraries to support Vue, as there are for React. PRs more than welcome.

**Comment by cezaraugusto** [comment]
Happy to share that support for Vue was added in #61 by @OSpoon 🚀🚀🚀

Will release v1.6.0 tomorrow which should include it. Thanks!
