### ISSUE TITLE
How to include polyfills for node apis?

### ISSUE THREAD

**Issue by breathingcyborg** [cezaraugusto/extension.js#55]
I'm trying to use a third party package that uses node apis like buffer, http etc. Is there a way i can include polyfill for these node apis? 

```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
	- install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "http": false }. Make sure to import the file correctly and that it exists in your extension's directory.
```

**Comment by cezaraugusto** [comment]
hi @breathingcyborg! could you describe the specific polyfills you need for this? do you rely on some specific library for the modules you need?

**Comment by breathingcyborg** [comment]
@cezaraugusto Thanks for this amazing devtool.

I was trying to use 'googleapis' package, it depends on lots of nodejs specific apis.

But since I only needed service account authentication from googleapis module, 
I was able to do it without 'googleapis' package, using jsrsasign.

**Comment by cezaraugusto** [comment]
that's great! thanks!
