### ISSUE TITLE
Could not resolve path ./scripts/content.js. Either add it to the "public" directory or create a script in the "scripts" directory.

### ISSUE THREAD

**Issue by ApacheAlpha** [cezaraugusto/extension.js#67]
**Create project**

yes | npx extension@latest create test --template=content

**Directory Structure**
![截图 2024-05-23 09-46-48](https://github.com/cezaraugusto/extension.js/assets/53244971/23346f37-4ec7-4937-b120-5fc010697efa)

**service-worker.js**

`chrome.action.onClicked.addListener((tab) => {
  console.log("=111=");
  console.log("====================================");
  chrome.scripting.executeScript({
    target: { tabId: tab.id },
    files: ["./scripts/content.js"],
  });
});
`

**content.js**

`import("../content.css");
console.log("====================================");
const blankDiv = document.createElement("div");
blankDiv.className = "content_script-area";
const title = document.createElement("h1");
title.className = "content_script-title";
title.textContent = "000";
blankDiv.appendChild(title);
document.body.appendChild(blankDiv);
`

**content.css**

`.content_script-title {
  font-size: 2.35em;
  color: #333;
  line-height: 1.1;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif;
  font-weight: 700;
  overflow-wrap: break-word;
  word-wrap: break-word;
  -ms-word-break: break-all;
  word-break: break-word;
}
.content_script-area {
  position: fixed;
  top: 50%;  
  right: 80px;
  width: 400px;
  height: 70%;
  background-color: rgb(250, 8, 8);
  z-index: 1000;
  transform: translateY(-50%); 
}`

**Service Worker**
###  May I ask why this question is prompted? Thank you so much

**service-worker.js:54 Could not resolve path ./scripts/content.js. Either add it to the "public" directory or create a script in the "scripts" directory.**

**actual effect**

Code can produce results

![截图 2024-05-23 09-44-01](https://github.com/cezaraugusto/extension.js/assets/53244971/6f111c55-0f68-49b0-b496-f93aaccbdf1a)

**Comment by cezaraugusto** [comment]
Hi @ApacheAlpha, thanks for reporting!

The error message you mentioned should only happen for standalone scripts, I created a sample repo to try to replicate the issue but could not reproduce using the code you provided. Here's a sample run:

https://github.com/cezaraugusto/extension.js/assets/4672033/d66e89af-fe71-465c-87e1-f31df3a8ab1c

Here is the repo I created using your code (extension used in the video): https://github.com/cezaraugusto/chrome-scripting-test.

Let me know if I missed something
